name: Build debian package for submodule

on:
  workflow_dispatch:
    inputs:
      package:
        description: "The package to build"
        required: true
        default: "pve-manager"
        type: string
  workflow_call:
    inputs:
      package:
        description: "The package to build"
        required: true
        default: "pve-manager"
        type: string

permissions:
  # for ghcr.io (docker registry):
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sed -i -e 's|git@github.com:|https://github.com/|' .gitmodules # switch from ssh to https because we don't have ssh keys in the pipeline
          git submodule update --init submodules/${{ inputs.package }}

          tag_latest=ghcr.io/hwinther/wsh-pve/${{ inputs.package }}:latest
          docker build . -f submodules/${{ inputs.package }}.Dockerfile -t $tag_latest
          docker push $tag_latest

          # test/list content of image:
          id=$(docker create $tag_latest)
          docker cp $id:/opt/repo/ ./build/
          docker rm -v $id
          ls -la build
