name: Build debian package for submodule when patch files are changed

on:
  workflow_dispatch:
  push:
    branches:
      - main
      # - 'fix/workflow-doc-chain'
    paths:
      - "submodules/pve-manager.patch"
      - "submodules/pve-qemu.patch"
      - "submodules/qemu-server.patch"
      - ".github/workflows/build-deb-trigger-patches.yml"

permissions:
  # for ghcr.io (docker registry):
  packages: write
  # to push changelog after package update:
  contents: write
  # for github pages:
  pages: write
  id-token: write

jobs:
  check:
    name: Check which files were changed
    runs-on: ubuntu-latest
    outputs:
      pve-manager: ${{ steps.changes.outputs.pve-manager }}
      pve-qemu: ${{ steps.changes.outputs.pve-qemu }}
      qemu-server: ${{ steps.changes.outputs.qemu-server }}
      pve-manager-count: ${{ steps.patch-count.outputs.pve-manager_changes }}
      pve-qemu-count: ${{ steps.patch-count.outputs.pve-qemu_changes }}
      qemu-server-count: ${{ steps.patch-count.outputs.qemu-server_changes }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            pve-manager:
              - 'submodules/pve-manager.patch'
            pve-qemu:
              - 'submodules/pve-qemu.patch'
            qemu-server:
              - 'submodules/qemu-server.patch'

      - name: Count amount of commits for each patch file
        id: patch-count
        run: |
          pve_manager_changes=$(git log --follow --pretty=oneline -- submodules/pve-manager.patch | wc -l)
          pve_qemu_changes=$(git log --follow --pretty=oneline -- submodules/pve-qemu.patch | wc -l)
          qemu_server_changes=$(git log --follow --pretty=oneline -- submodules/qemu-server.patch | wc -l)
          echo "pve-manager_changes=$pve_manager_changes" >> $GITHUB_OUTPUT
          echo "pve-manager_changes=$pve_manager_changes"
          echo "pve-qemu_changes=$pve_qemu_changes" >> $GITHUB_OUTPUT
          echo "pve-qemu_changes=$pve_qemu_changes"
          echo "qemu-server_changes=$qemu_server_changes" >> $GITHUB_OUTPUT
          echo "qemu-server_changes=$qemu_server_changes"

  build-pve-manager-deb-when-changed:
    uses: hwinther/wsh-pve/.github/workflows/build-deb.yml@main
    needs: [check]
    if: ${{ needs.check.outputs.pve-manager == 'true' }}
    with:
      package: pve-manager
    secrets: inherit

  build-pve-qemu-deb-when-changed:
    uses: hwinther/wsh-pve/.github/workflows/build-deb.yml@main
    needs: [check]
    if: ${{ needs.check.outputs.pve-qemu == 'true' }}
    with:
      package: pve-qemu
    secrets: inherit

  build-qemu-server-deb-when-changed:
    uses: hwinther/wsh-pve/.github/workflows/build-deb.yml@main
    needs: [check]
    if: ${{ needs.check.outputs.qemu-server == 'true' }}
    with:
      package: qemu-server
    secrets: inherit

  # debug-workflow:
  #   uses: hwinther/wsh-pve/.github/workflows/build-deb.yml@main
  #   needs: [check]
  #   with:
  #     package: pve-manager
  #   secrets: inherit

  update-docs-after-changes:
    # uses: hwinther/wsh-pve/.github/workflows/repo-update.yml@fix/workflow-doc-chain
    # needs: [build-pve-manager-deb-when-changed, build-pve-qemu-deb-when-changed, build-qemu-server-deb-when-changed, debug-workflow]
    # if: always()
    uses: hwinther/wsh-pve/.github/workflows/repo-update.yml@main
    needs: [build-pve-manager-deb-when-changed, build-pve-qemu-deb-when-changed, build-qemu-server-deb-when-changed]
    if: ${{ needs.check.outputs.pve-manager == 'true' || needs.check.outputs.pve-qemu == 'true' || needs.check.outputs.qemu-server == 'true' }}
  