name: Publish PVE build image

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/publish-pve-build-image.yml"
      - "build.Dockerfile"
  schedule:
    - cron: "30 5 1 * *"

permissions:
  # for ghcr.io (docker registry):
  packages: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          tag=ghcr.io/hwinther/wsh-pve/pve-build:13
          tag_latest=ghcr.io/hwinther/wsh-pve/pve-build:latest
          echo tag=$tag tag_latest=$tag_latest
          docker build . -t $tag -t $tag_latest -f build.Dockerfile
          docker push $tag
          docker push $tag_latest
