name: Publish reprepro (debian repo) image

on:
  workflow_dispatch:
  push:
    branches:
      - feat/public-deb-repo
    paths:
      - ".github/workflows/publish-reprepro-image.yml"
      - "reprepro.Dockerfile"

permissions:
  # for ghcr.io (docker registry):
  packages: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          tag=ghcr.io/hwinther/wsh-pve/reprepro:12
          tag_latest=ghcr.io/hwinther/wsh-pve/reprepro:latest
          echo tag=$tag tag_latest=$tag_latest
          docker build . -t $tag -t $tag_latest -f reprepro.Dockerfile
          docker push $tag
          docker push $tag_latest
