name: Publish djgpp build image

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/publish-djgpp-build-image.yml"
      - "djgpp.Dockerfile"

permissions:
  # for ghcr.io (docker registry):
  packages: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          tag=ghcr.io/hwinther/wsh-pve/djgpp-build:13
          tag_latest=ghcr.io/hwinther/wsh-pve/djgpp-build:latest
          echo tag=$tag tag_latest=$tag_latest
          docker build . -t $tag -t $tag_latest -f djgpp.Dockerfile
          docker push $tag
          docker push $tag_latest
