name: Updates master branches of local repos from upstream

on:
  workflow_dispatch:

permissions:
  actions: write
  packages: write
  contents: write
  pages: write
  id-token: write

jobs:
  trigger-sync-pve-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync-pve-manager
        run: gh workflow run sync-pve-manager.yml --ref main

  trigger-sync-qemu-server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync-qemu-server
        run: gh workflow run sync-qemu-server.yml --ref main

  trigger-sync-qemu-3dfx:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync-qemu-3dfx
        run: gh workflow run sync-qemu-3dfx.yml --ref main

  trigger-sync-pve-qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync-pve-qemu
        run: gh workflow run sync-pve-qemu.yml --ref main
