name: Updates master branches of local repos from upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "12 20 * * *"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/sync-from-upstream.yml"
      - ".github/workflows/sync-from-upstream-trigger.yml"

permissions:
  # for ghcr.io (docker registry):
  packages: write

jobs:
  sync-pve-manager:
    uses: hwinther/wsh-pve/.github/workflows/sync-from-upstream.yml@main
    with:
      repository: hwinther/pve-manager
    secrets: inherit

  sync-qemu-server:
    uses: hwinther/wsh-pve/.github/workflows/sync-from-upstream.yml@main
    with:
      repository: hwinther/qemu-server
    secrets: inherit

  pve-qemu:
    uses: hwinther/wsh-pve/.github/workflows/sync-from-upstream.yml@main
    with:
      repository: hwinther/pve-qemu
    secrets: inherit
