name: Updates master branch from upstream repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "The repository to sync"
        required: true
        default: "hwinther/pve-manager"
        type: string
      build_deb:
        description: "Build debian package when changes are detected"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      repository:
        description: "The repository to sync"
        required: true
        default: "hwinther/pve-manager"
        type: string
      build_deb:
        description: "Build debian package when changes are detected"
        required: false
        default: true
        type: boolean
    outputs:
      build-deb-when-changed-success:
        description: "Whether the build-deb-when-changed job succeeded"
        value: ${{ jobs.build-deb-when-changed.result == 'success' }}

permissions:
  # for ghcr.io (docker registry):
  packages: write
  # for creating releases via build-deb.yml:
  contents: write
  # for github pages:
  pages: write
  id-token: write

jobs:
  sync-from-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: "master"
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          echo basename=$(basename ${{ inputs.repository }})
          upstream_repo=$(echo ${{ inputs.repository }} | sed -e "s/hwinther/proxmox/")

          if [ "${{ inputs.repository }}" == "hwinther/qemu-3dfx" ]; then
            upstream_repo="kjliew/qemu-3dfx"
          fi

          echo upstream_repo=$upstream_repo
          git remote add upstream https://github.com/$upstream_repo.git
          git fetch upstream

          git checkout master
          git rebase upstream/master
          git push --force-with-lease origin master

  update-submodule:
    runs-on: ubuntu-latest
    needs: [sync-from-upstream]
    outputs:
      changed: ${{ steps.update-submodule.outputs.changed }}
      submodule: ${{ steps.update-submodule.outputs.submodule }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update submodule
        id: update-submodule
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          submodule=$(echo ${{ inputs.repository }} | sed -e 's|hwinther/||')
          echo submodule=$submodule
          echo "submodule=$submodule" >> $GITHUB_OUTPUT

          sed -i -e 's|git@github.com:|https://github.com/|' .gitmodules # switch from ssh to https because we don't have ssh keys in the pipeline
          git submodule update --init --remote submodules/$submodule
          git checkout -- .gitmodules # revert the change to .gitmodules
          changelogChanges=$(git diff --submodule=diff | grep "debian/changelog" | wc -l)
          if [ $changelogChanges -eq 0 ]; then
            echo No changes in debian/changelog
            echo "changed=false" >> $GITHUB_OUTPUT
            echo -e "\n\nSubmodule diff:"
            git diff --submodule=diff

            if [ "${{ inputs.repository }}" == "hwinther/qemu-3dfx" ]; then
              echo "qemu-3dfx is a special case, updating the reference to the submodule but skipping build"
            else
              exit 0
            fi
          fi

          git status
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            # Working directory clean - do nothing
            echo Working directory clean
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          else 
            # Uncommitted changes
            echo Add and commit changes
            git add submodules/$submodule
            git commit -m "Update submodule $submodule"
            git pull --rebase origin main # final rebase before pushing in case another pipeline changed it recently
            git push origin main
            if [ "${{ inputs.repository }}" == "hwinther/qemu-3dfx" ]; then
              echo "skipping build for qemu-3dfx (setting changed=false)"
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

  build-deb-when-changed:
    uses: hwinther/wsh-pve/.github/workflows/build-deb.yml@main
    needs: [update-submodule]
    if: ${{ needs.update-submodule.outputs.changed == 'true' && inputs.build_deb == true }}
    with:
      package: ${{ needs.update-submodule.outputs.submodule }}
    secrets: inherit
