name: Updates master branch from upstream repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "The repository to sync"
        required: true
        default: "hwinther/pve-manager"
        type: string
  workflow_call:
    inputs:
      repository:
        description: "The repository to sync"
        required: true
        default: "hwinther/pve-manager"
        type: string

jobs:
  sync-from-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: "master"
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # git clone https://github.com/${{ inputs.repository }}
          echo basename=$(basename ${{ inputs.repository }})
          # cd $(basename ${{ inputs.repository }})

          upstream_repo=$(echo ${{ inputs.repository }} | sed -e 's/hwinther/proxmox/')
          echo upstream_repo=$upstream_repo
          git remote add upstream https://github.com/$upstream_repo.git
          git fetch upstream

          git checkout master
          git rebase upstream/master
          git push --force-with-lease origin master

  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          submodule=$(echo ${{ inputs.repository }} | sed -e 's|hwinther/||')
          echo submodule=$submodule

          git submodule update --remote submodules/$submodule
          git push --force-with-lease origin master

          # cd submodules/$submodule
          # git checkout master
